baseurl = "https://xuehongyanl.github.io"
title = "Hongyan Xue"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

publishDir = "docs"

[params]
	author = "Hongyan Xue / 薛泓彦"
	authorShort = "Hongyan Xue"
	info = "PhD student & Developer"
	description = "Hongyan Xue's personal website"
	keywords = "blog,developer,personal"
	avatarurl = "images/avatar.jpg"
	#gravatar = "1141563180@qq.com"

	favicon_32 = "/img/favicon-32x32.png"
	favicon_16 = "/img/favicon-16x16.png"

	footercontent = "Let them hear the voice."
	hideFooter = false
	hideCredits = false
	hideCopyright = false
	since = 2021

	enableTwemoji = true

	colorScheme = "auto"
	hidecolorschemetoggle = false

	notByAI = true

	#customCSS = ["css/custom.css"]
	#customSCSS = ["scss/custom.scss"]
	#customJS = ["js/custom.js"]

[params.base]
	school = "IIP, ICT, CAS"
	schoolurl = "https://iip.ict.ac.cn/"
	city = "Beijing, China"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	author = "authors"

# Social links
[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 1
	url = "https://github.com/xuehongyanL/"
[[params.social]]
	name = "Mail"
	icon = "fa fa-envelope fa-2x"
	weight = 1
	url = "mailto:xuehongyan21b@ict.ac.cn"

# Menu links
[[menu.main]]
	name = "About"
	weight = 1
	url = "about/"
[[menu.main]]
	name = "CV"
	weight = 2
	url  = "CV.pdf"
[[menu.main]]
	name = "Publications"
	weight = 3
	url  = "publication/"
[[menu.main]]
	name = "Software"
	weight = 3
	url  = "software/"

[markup.goldmark.renderer]
	unsafe = true
